name: publish to nuget

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: msbuild package-test.csproj -property:Configuration=Release -property:Platform=AnyCPU -verbosity:m /p:version=1.0.0.0
      - name: Pack
        run: nuget pack package-test.csproj -Properties Configuration=Release
      - name: Push
        run: nuget push -src "https://nuget.pkg.github.com/mspry00/index.json" -ApiKey ${GITHUB_TOKEN} .\package-test.1.0.0.0.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    